default: &default
  username: <%= Rails.application.secrets.db_username %>
  password: <%= Rails.application.secrets.db_password %>
  database: <%= Rails.application.secrets.db_database %>
  adapter: 'mysql2'
  encoding: <%= Rails.application.secrets.db_encoding %>
  pool: <%= Rails.application.secrets.db_pool %>
  host: <%= Rails.application.secrets.db_host %>
  port: <%= Rails.application.secrets.db_port %>

development:
  <<: *default

test:
  <<: *default
  database: mercury_test

staging:
   <<: *default

qa:
   <<: *default

production:
  <<: *default